sudo: required

language: node_js

node_js:
  - "node"

services:
  - docker

env:
  matrix:
    - PHP_VERSION=php54 WP_VERSION=latest WP_MULTISITE=0 WC_VERSION=latest
    - PHP_VERSION=php55 WP_VERSION=latest WP_MULTISITE=0 WC_VERSION=latest
    - PHP_VERSION=php56 WP_VERSION=latest WP_MULTISITE=0 WC_VERSION=latest
    - PHP_VERSION=php70 WP_VERSION=latest WP_MULTISITE=0 WC_VERSION=latest

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install docker-engine --no-install-recommends -y -o Dpkg::Options::="--force-confmiss" -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew"
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.8.0-rc2/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin/
  - docker-compose -v
  - docker -v

install:
  - npm install && node_modules/.bin/grunt build
  - npm run start:${PHP_VERSION}
  - until [ "`docker inspect -f {{.State.Running}} ${PHP_VERSION}`" == "true" ]; do sleep 2; done

script:
  - npm run unit-test:js
  - npm run unit-test:${PHP_VERSION}