language: php

matrix:
  include:
    - php: "5.4"
      env:
        - PHP_FPM_DEFAULT=php-fpm.conf.default
        - PHP_FPM=php-fpm.conf
    - php: "7.0"
      env:
        - PHP_FPM_DEFAULT=php-fpm.d/www.conf.default
        - PHP_FPM=php-fpm.d/www.conf

addons:
  hosts:
    - woopos.dev

env:
  - WP_VERSION=latest WP_MULTISITE=0
  #    - WP_VERSION=latest WP_MULTISITE=1

before_install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install stable
  - git submodule update --init --recursive

install:
  # install wordpress & woocommerce & test theme
  - bash tests/unit/php/bin/install.sh woopos_tests root '' localhost $WP_VERSION
  - mkdir /tmp/wordpress/wp-content/plugins/woocommerce-pos/
  - mv * .[^.]* /tmp/wordpress/wp-content/plugins/woocommerce-pos/
  - mv /tmp/wordpress/* ./
  - git clone https://github.com/kilbot/WooCommerce-POS-Test-Theme.git wp-content/themes/WooCommerce-POS-Test-Theme
  - git clone https://github.com/kilbot/WooCommerce-POS-Test-Plugin.git wp-content/plugins/woocommerce-pos-test
  # apache
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/$PHP_FPM_DEFAULT ~/.phpenv/versions/$(phpenv version-name)/etc/$PHP_FPM
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # configure apache virtual hosts
  - sudo cp -f ./wp-content/plugins/woocommerce-pos/tests/integration/php/bin/travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - sudo service apache2 restart

before_script:
  # wp-cli
  - curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
  - chmod +x wp-cli.phar
  - sudo mv wp-cli.phar /usr/local/bin/wp
  - wp --info
  - wp core config --dbname=woopos_tests --dbuser=root
  - wp core install --url=woopos.dev --title=WooCommercePOS --admin_user=admin --admin_password=password --admin_email=support@woopos.com.au
  - wp rewrite structure '/%year%/%monthnum%/%postname%'
  - wp plugin activate woocommerce-pos
  - wp plugin activate woocommerce-pos-test
  - wp plugin install woocommerce --activate
  - wp plugin install wordpress-importer --activate
  - wp import wp-content/plugins/woocommerce/dummy-data/dummy-data.xml --authors=create
  - wp option update woocommerce_api_enabled yes
  - cp wp-content/plugins/woocommerce-pos/tests/integration/php/bin/wp-cli.yml ./
  - wp rewrite flush --hard
  # grunt-cli
  - cd wp-content/plugins/woocommerce-pos/
  - npm install -g grunt-cli
  - npm install
  - composer install

script:
  - grunt test
  - phpunit -c tests/unit/php/phpunit.xml
  - phpunit -c tests/integration/php/phpunit.xml
  #    - ./node_modules/.bin/pioneer

after_success:
  if [ $(phpenv version-name) == "7.0" ]; then
    phpunit -c phpunit.xml.dist
    php vendor/bin/coveralls -v
    grunt coverage
  fi