language: php

php:
    - 5.3
#    - 5.4

env:
    - WP_VERSION=latest WP_MULTISITE=0
#    - WP_VERSION=latest WP_MULTISITE=1
#    - WP_VERSION=3.8 WP_MULTISITE=0
#    - WP_VERSION=3.8 WP_MULTISITE=1

install
#    - sudo apt-get install build-essential
#    - sudo apt-get install subversion

before_script:
    - npm install -g grunt-cli
#    - sudo npm install
    - npm install
    - bash tests/php/bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
    - grunt test
    - phpunit