language: php

php:
    - 5.3
    - 5.4

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=3.8 WP_MULTISITE=0
    - WP_VERSION=3.8 WP_MULTISITE=1

before_script:
    - npm install -g grunt-cli
    - npm install /home/travis/build/kilbot/WooCommerce-POS/
    - bash tests/php/bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
    - phpunit